### ISSUE TITLE
Game status indicator in chat user list

### ISSUE THREAD

**Issue by Cheyans** [micheljung/downlords-faf-client#76] opened 2015-08-14 02:47 UTC
![image](https://cloud.githubusercontent.com/assets/8811789/9266267/be6b4678-420c-11e5-9ff5-9e242d6ee4af.png)

I think the current icons for the client is fine, also there seems to be a host icon which is nice
https://github.com/FAForever/client/tree/develop/res/chat/status

i was thinking set the state of each player in irc depending on the gameinfo returned from the server. Maybe have an enum property that listens to gameInfo status

**Comment by Cheyans** [comment] 2015-08-14 03:43
Ok I just realized we'll have to listen to every single game status which was the issue we were having in the past, this maybe a thing we want to address sooner than later.

**Comment by micheljung** [comment] 2015-08-14 11:40
What do you mean? We're already listening for all game status updates, and I don't know what issue you mean :-)
Anyway, this is a duplicate of #7 but since it has a better description I'm going to close #7 and schedule this one instead.

**Comment by Cheyans** [comment] 2015-08-14 13:22
Well, my plan was to have the chatuser have a enum attribute that is changed based on whether game status of gameinfo bean is open, playing or closed (not sure if unknown is ever used). I wanted a listener  on the gameinfobean game status which then updates all the chatusers listed in gameinfobean, but what I guess I could do is a have method within gameinfobean which updates all the chatusers based on the playerlist in gameinfobean. So a push kind of style rather than listener.

**Comment by micheljung** [comment] 2015-08-14 13:28
Let `PlayerService` register itself to `GameService` as an `OnGameInfoListener` and update the `PlayerInfoBean` accordingly.

GameInfoBean shouldn't be a listener nor have any method other than getter/setter/property.

**Comment by Cheyans** [comment] 2015-08-15 03:23
Wont this mean that every individual player is listening on the gameInfo meaning possibly 100+ listeners rather than the gameInfos pushing updates to the playerInfo meaning 20+ listeners

**Comment by Cheyans** [comment] 2015-08-15 04:37
So after writing it my way, gameInfo is consistently checking each player, if their state is the same as the gamestate, who is host etc. Is this consistent checking of many properties more taxing or is having a large amount of listeners and updating their fields accordingly?

**Comment by micheljung** [comment] 2015-08-16 10:41
No, you'd have exactly one listener. `PlayerService` listens on `GameService`. It receives a `GameInfoBean` that contains a list of players that are in that game (plus who's host). It iterates over that list of names, looks up the according `PlayerInfoBean` and sets the status value.

`GameInfo` is a data object and shouldn't have any behavior. It's only for deserialization of server messages.

**Comment by Cheyans** [comment] 2015-08-17 02:20
Should playerinfobean be aware of what game the player is in or shall that be something that the gameservice checks, seems a little inefficient if the latter in that the it would have to iterate over all gameinfobeans with every check.

**Comment by micheljung** [comment] 2015-08-17 09:48
I think it's fine to have a `private IntegerProperty currentGameUid` in player info bean. Lookuo can then be made using the gameservice. We could also referencing the gameinfobean but i have the feeling we shouldnt do that :P

**Comment by Cheyans** [comment] 2015-09-03 12:49
Adding gamestatus tooltip

**Comment by micheljung** [comment] 2015-09-06 12:04
This has not yet been merged into master, pushing back

**Closed** 2015-11-24 02:28 UTC
Labels: enhancement

**Comment by Cheyans** [comment] 2015-11-24 02:31
#103
