### ISSUE TITLE
Disconnect from everyone

### ISSUE THREAD

**Issue by tatsujb** [micheljung/downlords-faf-client#201] opened 2016-03-01 20:45 UTC
very sporadic.

happens only on Downlords's client :(
dunno what's causing it. 

disconnection is very sudden and from everyone. internet continues to function
reconnecting to others is impossible.

**Comment by micheljung** [comment] 2016-03-01 20:53
I know this problem exists but I haven't investigated yet :\
I'm glad for anyone who tests, but I still wouldn't use my client for regular gaming before it reaches Beta :-)

**Comment by tatsujb** [comment] 2016-03-01 22:24
here

**Comment by tatsujb** [comment] 2016-03-01 22:31
https://drive.google.com/file/d/0BzN9wSaRvA86VWk0SnlKaTlqSkE/view?usp=sharing is this it?

**Comment by micheljung** [comment] 2016-03-01 23:55
do you know what date/time the problem occurred?

**Comment by micheljung** [comment] 2016-05-10 17:41
This was supposedly caused by memory leaks which are fixed now.

**Closed by micheljung** 2016-05-10 17:41 UTC
Labels: bug
